### PR TITLE
Create sv.ts

### PR DESCRIPTION
**Pull request by eson57**
Swedish translation

### CODE REVIEW

**Comment by custodian** [comment]
Warehouse translations are managed with transifex: https://www.transifex.com/projects/p/warehouse/
Translations are automatically pulled from translation service on each build.
You may want to add and maintain swedish translation, so it would not get overrided.

**Comment by eson57** [comment]
Ok... I'll do that.

**Comment by custodian** [comment]
You may import .ts file into tranlsation project.
I'll reopen this pull request and merge the file

**Comment by eson57** [comment]
Thanks!

**Pull request merged**
